export const ADD_USER_NAME = 'ADD_USER_NAME';
export const ADD_NEW_INVENTORY = 'ADD_NEW_INVENTORY';
export const UPDATE_INVENTORY = 'UPDATE_INVENTORY';
export const ADD_NEW_INVENTORY_ITEM = 'ADD_NEW_INVENTORY_ITEM';
export const UPDATE_INVENTORY_ITEM = 'UPDATE_INVENTORY_ITEM';